version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_CREATE_TOPICS: "stock:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  producer:
    build: './producer'
    depends_on:
      - kafka
    volumes:
     - .:/code
  consumer:
    build: './consumer'
    depends_on:
      - kafka
    volumes:
     - .:/code
